[package]
name = "lib-plant-uml"
version = "0.1.0"
edition = "2024"

[dependencies]
lib-core = { path = "../lib-core/" }
pest = "2.8.1"
pest_derive = "2.8.1"

[dev-dependencies]
pretty_assertions = { workspace = true }
