[workspace]
resolver = "3"
members = [
  "crates/libraries/ascii",
  "crates/libraries/cli",
  "crates/libraries/plant_uml",
  "crates/applications/plant_uml_ascii_renderer_cli",
  "crates/libraries/uml",
]

[workspace.dependencies]
pretty_assertions = "1.4.1"
